### ISSUE TITLE
Specify Tab delimiter

### ISSUE THREAD

**Issue by nickybpm** [lzakharov/csv2md#13]
I'm workign with some "TSV" (tab delimited) files. I haven't figured out how to specify tab as a delimiter, since it's not really possible to type a tab into my shell. Is there some way to do it?

**Comment by lzakharov** [comment]
Yes, sure. You can pass your custom delimiter via `-d` (or `--delimiter`) flag. You can run `csv2md -h` to see more information about the available options.

**Comment by nickybpm** [comment]
Thank you for the reply. I understand that there is the -d flag, but I don’t know how I can use that to set the delimiter to be Tab, since Tab is a non-printable character. I can’t type a character to represent it.

**Comment by nickybpm** [comment]
After researching the matter, I've found it _is_ indded possible to specify a non-printing characters as an argument on the command line.

For anyone else reading this, the required incantation is:

`csv2md -d $'\t' myfile`

I tested this in `zsh`, but I expect it should work in other shells too.

Thanks again for your attention, and a great tool.

**Comment by nickybpm** [comment]
I tested it and it works with `bash` as well as `zsh`. I've dropped a PR in case you'd like to add it to the docs.

**Comment by lzakharov** [comment]
Thanks for your research, really appreciate it! Your question is related to working on the command line in general and I've found [this explanation](https://unix.stackexchange.com/a/35370) useful too.
