### ISSUE TITLE
Ability to filter columns

### ISSUE THREAD

**Issue by xavivars** [lzakharov/csv2md#15]
It would be great if there was an easy way to provide a list of columns to be used when converting to markdown

So, for example, with a table with 10 columns, doing something like 

    --use-only=1-3,4,5,7

would not include columns 6, 8 9 and 10 into the generated table

**Comment by lzakharov** [comment]
Hi, @xavivars!
Good point, would be nice to have it. As a quick solution, I can suggest you to use [csvgrep](https://csvkit.readthedocs.io/en/latest/scripts/csvgrep.html) with option `--columns` to filter columns and provide result to the `csv2md`. Anyway, I'll try to add this feature to `csv2md` soon. Also if you want to contribute and add this option yourself, that would be great.
