### ISSUE TITLE
Support headings output in addition to tables

### ISSUE THREAD

**Issue by paddy74** [lzakharov/csv2md#19]
## Description

I have a requirement to translate a CSV file into a set of Markdown headings and bullets. Due to this library's efficiency and small profile, it would be straightforward to add an additional function to `table.py` which will do so.

### Desired Functionality

- Add one additional function `Table.markdown_headings`.
- Add two additional arguments specific to this function:
  - An argument that indicates what column is the top-level heading for each row
  - An argument that indecates what heading level the top-level heading for each row will be

#### Input

`csv2md table.csv --output-headings --heading-column=0 --heading-level=2`

#### Output

```md
## **Col-A Row-1 Label**: Col-A Row-1 Value

- **Col-B Row-1 Label**: Col-B Row-1 Value
- **Col-C Row-1 Label**: Col-C Row-1 Value

## **Col-A Row-2 Label**: Col-A Row 2 Value

...and so on...
```

## Addtional Suggestions

Future work would allow a user to:

- Indicate a subset of columns to be sub-headings

**Comment by lzakharov** [comment]
Hi! Thank you for your suggestion. This utility focused on the one feature - converting CSV files into Markdown tables. Unfortunately, the proposed format seems too specific and does not fit into the above concept. I think that a more correct solution would be to implement such feature into a separate tool. I will be glad if `csv2md` will be used for this tool as library.
