### ISSUE TITLE
1.0.1 removed from pypi?

### ISSUE THREAD

**Issue by andrewsmartin** [lzakharov/csv2md#6]
Hello,

I just wanted to point out that it seems that v 1.0.1 has been removed from pypi - I see that 1.1.1 was released earlier today, but there appear to be no previous versions on pypy: https://pypi.org/project/csv2md/#history

Were earlier artifacts intentionally removed? Any chance you'd be able to republish that version by checking out the commit for 1.0.1?

**Comment by lzakharov** [comment]
Hello!

Unfortunately, previous artifacts were accidentally deleted. I've republished previous version (`1.0.1`) as `1.0.2` because PyPI doesn't allow to [reuse file names](https://pypi.org/help/#file-name-reuse). I apologize for the inconvenience!

**Comment by andrewsmartin** [comment]
Thanks for the quick response and follow up!
