### ISSUE TITLE
set encoding to UTF-8 (for special characters)

### ISSUE THREAD

**Issue by DarmstadtBri** [lzakharov/csv2md#7]
tables with "ä" "ö" etc. are not generating correctly.

**Comment by lzakharov** [comment]
@DarmstadtBri, thanks for the contribution! I'll try to fix this as soon as possible. If not difficult, send a minimal example with _expected_ and _actual_ results.

**Comment by DarmstadtBri** [comment]
Hi Lev,

Thanks for writing the library! Attached is a sample table and result. Maybe you could add a parameter for encoding.

Another error: If the CSV contains empty lines, it writes an empty markdown table.

Cheers,

Brian

Von: Lev Zakharov<mailto:notifications@github.com>
Gesendet: Freitag, 14. Februar 2020 12:57
An: lzakharov/csv2md<mailto:csv2md@noreply.github.com>
Cc: Brian Junker-Latocha<mailto:brianjunker@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [lzakharov/csv2md] set encoding to UTF-8 (for special characters) (#7)


@DarmstadtBri<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDarmstadtBri&data=02%7C01%7C%7C0bf522bff444434c136208d7b14511df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637172782514041279&sdata=1DHZY8Nu7AUTli4MrD1gDCZ30NU9uQSS%2Fd637SNscDg%3D&reserved=0>, thanks for the contribution! I'll try to fix this as soon as possible. If not difficult, send a minimal example with expected and actual results.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzakharov%2Fcsv2md%2Fissues%2F7%3Femail_source%3Dnotifications%26email_token%3DAGFNWZH3RHXKMAZLOTTLPKTRC2BKTA5CNFSM4KVGHYCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELYZPSA%23issuecomment-586258376&data=02%7C01%7C%7C0bf522bff444434c136208d7b14511df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637172782514051274&sdata=25Y3G9WyRTuNfx1Pv42dKgnV6qS618y%2B2Y961jZLLMc%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFNWZCTIYQCLZ7SX56CD2DRC2BKTANCNFSM4KVGHYCA&data=02%7C01%7C%7C0bf522bff444434c136208d7b14511df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637172782514061269&sdata=8d5a%2BL%2BQ%2Fflsa2opvHFm4cMSdp6J5Nr1nkDzDZoDh2g%3D&reserved=0>.


| word;status       |
| ----------------- |
| Ãœber;bad         |
| Redefreiheit;good |
| FuÃŸball;bad      |
| Ã¶stlich;bad      |
| FÃ¤hre;bad        |
| noUmlaut;good     |
| Weizen;good       |
| Korn;good         |

**Comment by DarmstadtBri** [comment]
[testOutput.txt](https://github.com/lzakharov/csv2md/files/4204915/testOutput.txt)

**Comment by DarmstadtBri** [comment]
Original CSV:

word;status
Über;bad
Redefreiheit;good
Fußball;bad
östlich;bad
Fähre;bad
noUmlaut;good
Weizen;good
Korn;good

**Comment by DarmstadtBri** [comment]
> Hi Lev, Thanks for writing the library! Attached is a sample table and result. Maybe you could add a parameter for encoding. Another error: If the CSV contains empty lines, it writes an empty markdown table. Cheers, Brian | word;status | | ----------------- | | Ãœber;bad | | Redefreiheit;good | | FuÃŸball;bad | | Ã¶stlich;bad | | FÃ¤hre;bad | | noUmlaut;good | | Weizen;good | | Korn;good |

I have opened a separate issue for the ";" delimiter not working.

**Comment by lzakharov** [comment]
It still working for me fine:

```bash
csv2md a.csv -d ";" > a.md
```

Original CSV and result: [archive.zip](https://github.com/lzakharov/csv2md/files/4205157/archive.zip).

Maybe you need check encoding on your host machine?

**Comment by DarmstadtBri** [comment]
> It still working for me fine:
> 
> ```shell
> csv2md a.csv -d ";" > a.md
> ```
> 
> Original CSV and result: [archive.zip](https://github.com/lzakharov/csv2md/files/4205157/archive.zip).
> 
> Maybe you need check encoding on your host machine?

Aha. I did not save to file, but copied out of the console

**Comment by lzakharov** [comment]
> > It still working for me fine:
> > ```shell
> > csv2md a.csv -d ";" > a.md
> > ```
> > 
> > 
> > Original CSV and result: [archive.zip](https://github.com/lzakharov/csv2md/files/4205157/archive.zip).
> > Maybe you need check encoding on your host machine?
> 
> Aha. I did not save to file, but copied out of the console

Hm, maybe you have to set encoding to UTF-8 in your terminal:)

**Comment by DarmstadtBri** [comment]
Strange, even when I write to file I get this on windows:
[mdTable.txt](https://github.com/lzakharov/csv2md/files/4205236/mdTable.txt)

**Comment by DarmstadtBri** [comment]
> Strange, even when I write to file I get this on windows:
> [mdTable.txt](https://github.com/lzakharov/csv2md/files/4205236/mdTable.txt)
> 
> word	status
> ├£ber	bad
> Redefreiheit	good
> Fu├ƒball	bad
> ├╢stlich	bad
> F├ñhre	bad
> noUmlaut	good
> Weizen	good
> Korn	good

The symbols have changed strangely.

**Comment by lzakharov** [comment]
I'm totally sure that windows tries to write the result with it's own encoding. That's why you get such result. I've opened my `a.md` with `win-1251` encoding and got the same strange symbols. Unfortunately, I haven't used Windows for five years and don’t know how to help you. Maybe you need to change global system encoding to UTF-8.

**Comment by DarmstadtBri** [comment]
> I'm totally sure that Windows tries to write the result with it's own encoding. That's why you get such result. I've opened my `a.md` with `win-1251` encoding and got the same strange symbols. Unfortunately, I haven't used Windows for five years and don’t know how to help you. Maybe you need to change global system encoding to UTF-8.

Ok, that could well be the case. Thanks for the help.

**Comment by DarmstadtBri** [comment]
Tried it on another windows computer even, and it is working fine. Must be a setting on my other machine.
