### ISSUE TITLE
Setting delimiter to semicolon does not always work

### ISSUE THREAD

**Issue by DarmstadtBri** [lzakharov/csv2md#8]
Even when using the -d ";" parameter, sometimes I have to change the delimiter in the source file for it to work.

| word;status       |
| ----------------- |
| Ãœber;bad         |
| Redefreiheit;good |
| FuÃŸball;bad      |
| Ã¶stlich;bad      |
| FÃ¤hre;bad        |
| noUmlaut;good     |
| Weizen;good       |
| Korn;good         |

**Comment by lzakharov** [comment]
Thanks for issue! Now it works. Please upgrade your version to the `1.1.2`.

**Comment by DarmstadtBri** [comment]
> Thanks for issue! Now it works. Please upgrade your version to the `1.1.2`.

Thanks a lot!
